### PR TITLE
Rely only on sales api interfaces

### PR DESCRIPTION
**Pull request by SamTay**
@jksimoniii @emberdyn

### CODE REVIEW

**Comment by SamTay** [comment]
@jksimoniii pingadingringringring

**Comment by SamTay** [comment]
ring a ding ding ping ping @emberdyn @jksimoniii make sure you guys are good with this

**Comment by jksimoniii** [comment]
@SamTay This seems like an asinine approach just to load an order model!?!?

Is this the way the really intend us doing loads?

**Comment by SamTay** [comment]
If we just want data yes. This is how we abstract ourselves from the core. This is also how upgrades will be easier. We are guaranteed those repository interface methods will be around in the future. What if a later update makes load by increment I'd protected?

**Pull request merged**
